# Generated by Django 5.1.7 on 2025-05-05 22:13

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('profile_pic', models.ImageField(blank=True, help_text='Upload your profile picture', null=True, upload_to='', verbose_name='Profile picture')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself', null=True, verbose_name='User bio')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], help_text='Gender', max_length=1, null=True, verbose_name='User Gender')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter phone number with country code', max_length=128, null=True, region=None, unique=True, verbose_name='Phone number')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
                ('followers', models.ManyToManyField(related_name='following', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'abstract': False,
            },
        ),
    ]
